name: React CI

on:
  push:
    branches:
      - main  # Trigger on push to the main branch
  pull_request:
    branches:
      - main  # Trigger on pull requests targeting the main branch

jobs:
  build:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner

    steps:
    - name: Checkout code
      uses: actions/checkout@v3  # Checkout the repository code

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'  # Set the Node.js version (change if needed)

    - name: Install dependencies
      run: |
        npm install  # or `yarn install` if using Yarn

    - name: Run tests
      run: |
        npm test -- --coverage  # Run tests and generate coverage report

    - name: Build
      run: |
        npm run build  # Build the project for production

    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: react-app-build
        path: build  # Path to the build output directory

    - name: Deploy
      if: github.ref == 'refs/heads/main'  # Deploy only on the main branch
      run: |
        echo "Deploying to production server..."
        # Add deployment scripts or commands here
